repos:
  # Backend Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.*\.md|.*\.txt)$
      - id: end-of-file-fixer
        exclude: ^(.*\.md|.*\.txt)$
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-docstring-first

  # Python code formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: [ruff==0.8.4]
      - id: ruff-format
        additional_dependencies: [ruff==0.8.4]

  # Python type checking (disabled due to many type annotation issues)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [
  #         types-requests,
  #         types-redis,
  #         django-stubs,
  #         djangorestframework-stubs,
  #       ]
  #       args: [--ignore-missing-imports]

  # Frontend JavaScript/TypeScript hooks (disabled due to ESLint v9 compatibility issues)
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.15.0
  #   hooks:
  #     - id: eslint
  #       files: ^frontend/
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@^9.15.0
  #         - eslint-config-next@15.5.3
  #         - "@eslint/eslintrc@^3"
  #       args: [--fix, --max-warnings=0, --config=frontend/eslint.config.mjs]

  # Frontend formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md)$
        additional_dependencies:
          - prettier@^3.1.0

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: debug-statements
