[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"