[build]
  command = "npm install --prefix frontend && npm install --prefix netlify && npm run build --prefix frontend"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"