# Generated by Django 5.2.6 on 2025-09-22 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('hashed_key', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_profile', models.CharField(default='default', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('client_hash', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['client_hash', 'expires_at'], name='core_client_client__72d359_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateLimitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=128)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('budget_remaining', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-window_start'],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'window_start', 'window_end'), name='unique_bucket_window')],
            },
        ),
    ]
