# Generated by Django 5.2.6 on 2025-09-22 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factoids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='created', max_length=32)),
                ('client_hash', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(default='usd', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='factoids.generationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_f206fe_idx')],
            },
        ),
    ]
