name: Generate Factoid

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  generate-factoid:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request to Netlify function
        env:
          NETLIFY_FUNCTION_URL: https://andys-daily-factoids.com/.netlify/functions/generateFactoid
          FUNCTIONS_API_KEY: ${{ secrets.FUNCTIONS_API_KEY }}
        run: |
          curl -X POST $NETLIFY_FUNCTION_URL \
            -H "Content-Type: application/json" \
            -H "x-api-key: $FUNCTIONS_API_KEY"
